version: "3.8"

volumes:
  db:
  data:
  config:
  logs:
  plugins:
  client-plugins:

services:
  db:
    build:
      context: db
      args:
        - BUILDKIT_INLINE_CACHE=1
      cache_from:
        - alinpanaitiu/mattermost-db:latest
    image: alinpanaitiu/mattermost-db:${TAG:-latest}
    container_name: mattermost-db
    read_only: true
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=mattermost
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    build:
      context: app
      args:
        - BUILDKIT_INLINE_CACHE=1
        - edition=team
        - MM_VERSION=5.33.3
      cache_from:
        - alinpanaitiu/mattermost:latest
    image: alinpanaitiu/mattermost:${TAG:-latest}
    container_name: mattermost
    restart: unless-stopped
    volumes:
      - config:/mattermost/config:rw
      - data:/mattermost/data:rw
      - logs:/mattermost/logs:rw
      - plugins:/mattermost/plugins:rw
      - client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
      # When you want to use SSO with GitLab, you have to add the cert pki chain of GitLab inside Alpine
      # to avoid Token request failed: certificate signed by unknown authority (link: https://github.com/mattermost/mattermost-server/issues/13059)
      # - <path_to_your_gitlab_pki>/pki_chain.pem:/etc/ssl/certs/pki_chain.pem:ro
    ports:
      - "8009:8000"
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=${POSTGRES_PASSWORD}
      - MM_DBNAME=mattermost

      # use the credentials you've set above, in the format:
      # MM_SQLSETTINGS_DATASOURCE=postgres://${MM_USERNAME}:${MM_PASSWORD}@db:5432/${MM_DBNAME}?sslmode=disable&connect_timeout=10
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:${POSTGRES_PASSWORD}@db:5432/mattermost?sslmode=disable&connect_timeout=10
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json
